### ISSUE TITLE
Solution Issue

### ISSUE THREAD

**Issue by robgw84** [Alya-N/C-Hero-Calc#12]
I have noticed that when I try and find out what number of followers it would take me to finish a quest with my current heroes, the calculator will pick 2 heroes and then the lowest monster that can beat the quest with those two heroes. This results in it giving me a higher follower requirement than it needs.

**Comment by Alya-N** [comment]
Did you modify the lower follower limit(lowest monster value to consider for calculations) and upper follower limit(how many followers you have)?

**Comment by robgw84** [comment]
I set the lower limit to 60% of my followers and then changed the upper to -1. I currently have 68 million followers, it immediately gave 72 million followers but only by using 2 heroes and 1 monster. It ignored any 4 unit solutions that may have been possible with less followers.

**Comment by Alya-N** [comment]
That's because it tries 3 unit solutions first and finds something that works.
I believe older calc iterations had an option to continue until the lowest follower amount has been achieved, but I don't know how to enable it. I'll look it up.

**Comment by Alya-N** [comment]
Try opening default.cqconfig and setting "STOP_FIRST_SOLUTION" to FALSE instead of true. That might be what you're looking for.

**Comment by Alya-N** [comment]
Not sure if that solved it, but I haven't seen a reply from you in nearly 2 weeks, so I'll mark it as solved.
