### ISSUE TITLE
Wrong stats?

### ISSUE THREAD

**Issue by Farario** [Alya-N/C-Hero-Calc#16]
A solution the calc gave me for a dq with an f30 was Rua p3 (383 attack) and maxed Hattori (355+11) with leaves the f30 alive with 2 hp. While normally they'd deal 932 damage, there's an Erebus:1k behind that gives it +2 armor. I think the error here might be that Rua is hitting an air monster before and only hitting the f30 with ricochet, so the calc might not get that it needs to apply armor to the ricochet hit.
Edit: Wait, no that'd still be 930 damage, it looks like it completely ignored Erebus giving it 4 armor through two hits.

**Comment by Farario** [comment]
Btw, the inaccurate title it because my initial suspicion was that one of the two had a wrong attack stat in the calc.

**Comment by Alya-N** [comment]
It is a bug with applying armor to ricochet hits, since the new battle system applies armor to each ricochet hit, when it didn't in the old system. Will take a while to fix, that is a huge change to the calc, when the calc only calculates armor for the front unit.

**Comment by Alya-N** [comment]
Latest calc update should have fixed it.
