### ISSUE TITLE
DQ wrong result?

### ISSUE THREAD

**Issue by Farario** [Alya-N/C-Hero-Calc#20]
<img width="547" alt="1" src="https://user-images.githubusercontent.com/43454642/50648594-f2c68000-0f7b-11e9-9939-1f54bc9faa87.png">
So for my dq, I'm getting this lineup, which does not actually solve the quest. Best guess would be a wrong attack stat on Lee? Or something weird with Reflect. Because if Lee takes out Xarth in one hit and has his reflect then hit Hal, the battle would end up a win as far as I can see. And indeed, just putting something in between Lee and Rua to weaken Xarth easily ends up as a win. 
Using the most recent version from a few hours ago.

**Comment by Alya-N** [comment]
I've fixed the issue with S4 and now it shows this solution:
```
Solution for [Followers: 1,012,931,000 | putrid:1000 hallinskidi:1000 xarth:1000 w30 e30 <==]:
  [Followers:       0 | werewolf:99 masterlee:99.2 sexysanta:99.4 ashygu:87 rua:99.4 <==]

  306 Fights simulated.
  Total Calculation Time: 1
  Calc Version: 4.0.1.1e

Battle Replay (Use on Ingame Tournament Page):
eyJzZXR1cCI6Wy01MywtMTA0LC03OCwtMTIwLC04NiwtMV0sInNoZXJvIjp7Ijg0Ijo5OSwiMTE4Ijo4NywiNzYiOjk5LCIxMDIiOjk5LCI1MSI6OTl9LCJzcHJvbW8iOnsiODQiOjQsIjc2Ijo0LCIxMDIiOjJ9LCJwbGF5ZXIiOlstMTEzLC02NSwtNDgsMTE5LDExNywtMV0sInBoZXJvIjp7IjQ2IjoxMDAwLCI2MyI6MTAwMCwiMTExIjoxMDAwfSwicHByb21vIjp7fX0=
```

**Comment by Farario** [comment]
Ah, that's about what I ended up using and while the solution the updated calc spits out is different now thanks to other heroes I have, it also works.
