### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by LudoKressh** [Alya-N/C-Hero-Calc#24]
maybe due to Seethe : 

> Solution for [Followers:       0 | lordofchaos:1 <==]:
>   [Followers:       0 | seethe:99 aathos:66 drhawking:99.4 abavah:67 ashygu:66 cliodhna:99.3 <==]
> 
>   Boss Damage Done: 12,390
>   102277344 Fights simulated.
>   Total Calculation Time: 94
>   Calc Version: 4.1.3.0b
> 
> Battle Replay (Use on Ingame Tournament Page):
> eyJzZXR1cCI6Wy0xNDQsLTY4LC0xMDMsLTEwMiwtMTIwLC0xMzFdLCJzaGVybyI6eyIxMjkiOjk5LCIxMTgiOjY2LCIxMDAiOjY3LCIxMDEiOjk5LCI2NiI6NjYsIjE0MiI6OTl9LCJzcHJvbW8iOnsiMTI5IjozLCIxMDEiOjR9LCJwbGF5ZXIiOlstNzQsLTEsLTEsLTEsLTEsLTFdLCJwaGVybyI6eyI3MiI6MX0sInBwcm9tbyI6e319
> 
> This does not beat the lineup!!!
> FATAL ERROR!!! Please comment this output in the Forums!

**Comment by Alya-N** [comment]
Thank you. Apparently this bug has been there for a while, and Seethe wasn't affected by AoE if he was in the last position of a found solution.
Fixed in 4.1.3.0c

**Comment by LudoKressh** [comment]
Thank you very much for your work on the solver.
