### ISSUE TITLE
Wasn't there a way to redo heroes?

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#25]
When you would click Y for doing another line up, wasn't it possible before to do it with new heroes as well?
I'm almost positive there was, because I had a batch file that would do it. Now it's not working. Just lets you do a new line up of enemies now, but keeps the currently selected heroes.
I'm trying to do a batch file that will allow multiple attempts to do quests with different heroes. Specifically the Promotion quests.
Like have it run with Ageum and another 2, then ageum, and another set of 2, and so on.
But can't seem to do it now.

Well, technically, I DO know how to do it, but I'll be damned if I want to create 7.6K different files for every promotion.

But yeah, I'm SURE there was a way to change your heroes. Dice or nls0 or Gizmo or hw1-5 or _someone_ removed it for some silly reason. People were annoyed that they had to keep adding in heroes and min/max followers again I guess. Rather than make it an option.

**Comment by Vitae666** [comment]
Lord help me, but I actually went this route. And got it to work. Long convoluted and hellish. And after it was done, I didn't even have a solution to be able to Promote AGeum. LOL!

- 1 permutation website
- 1 Excel export to separate files script. 7656 files
- NotePad++
- 1 batch file with 7656 dump to file entries and 7656 delete file entries
- 1 auto clicker because the stupid files and batch file refuse to allow me to send an Enter after saying "no" to running another line up and there's no "auto close" feature after saying "no" but have to "press enter to exit"

Only took me 6hrs (12am to 6am) to figure out how to do everything and run multiple tests.
FML 
We really need the -4 version to know that a Hero is mandatory to the solution.

**Comment by Alya-N** [comment]
Sorry, I've looked through the whole calc commit history, and I couldn't find the feature that you've described. Unfortunately, I still haven't managed to find a way to implement .2 promotions, so if anyone has an idea on how to do that, they are welcome to update the calc since it's open-source. 
Fortunately, pebl has listed most of the .2 solutions in this convenient spreadsheet, so you can use it to check what you need: https://docs.google.com/spreadsheets/d/1pWdJ7XJt6_KE0B4QCoR6r52sPlwq0Hy5VvQzp6k5P5E/edit#gid=741717594

**Comment by Vitae666** [comment]
It's all good. there was a commit where it allowed outside files (Before the whole cqinput thing I think.)
You could run it and it would just redo the heroes and stuff based on the file. Looking for it now wouldn't matter to much cause of the new heroes. Would have to figure which one was it with older heroes and pre-lvl 99 stuff. More hassle than it's worth. Would make my 7.6K file method easy by comparison :)
Think this was the one that I'm talking about.
Allow for "config" file to be passed as a command line argument
https://github.com/hw1-5/C-Hero-Calc/commit/34127e10f757b7fe84611275c10e4da44516e51c#diff-be1c7b245c90f843334e1e970bfdd614

Kewl on the sheet. didn't know about it. Will have to take a look.
Flint.4 means what? Flint on the 4th promotion right?
And what's the #'s in D column? Can't be followers cause there's no monsters being used.

**Comment by Alya-N** [comment]
From the WARNING tab of the spreadsheet: 
```
The random number is an attempt to convert to PG; CC2PG=1, UM2PG=6, AS2PG=10000
```
And .4 indeed means 4th promotion.
I don't think I can implement what you're talking about now, I'm afraid that could break the interaction between calc and macro.

**Comment by Vitae666** [comment]
Duh. Helps if I'd read that. Sorry :)
Adding a "Do you want to re-enter heroes? (Y/N)" after saying yes to a "new line up" you mean?
I guess it might. Dunno. I'll just stick with my 7.6K files. Only takes about 10 minutes to do everything anyways now that I know what I'm doing and how to do it :)
Think the Sheet is a bit Hero advanced for me tho. Still really need to check into it.
