### ISSUE TITLE
Different results with lower Min Followers?

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#30]
Thought this type of error had been taken care of. I remember it in the forums a looong time ago.
1st one has lower limit of 145,532,636
2nd one has a lower limit of 100
2nd one works where as the 1st one fails.
I've included both results files and the Heroes List file for import and test if you want.

> Set a lower follower limit on monsters used: 145532636 
> Set an upper follower limit that you want to use: 484905517 
> Enter Enemy Lineup(s): quest138-3 
> 
> Calculating with 11 available Monsters and 115 enabled Heroes.
> Starting loop for armies of size 1
> Starting loop for armies of size 2
> Starting loop for armies of size 3+
> 
> Solution for [quest138-3 | Followers: 951,416,500 | a27 a27 w30 f28 w30 a27 <==]:
>   Could not find a solution that beats this lineup.
> 

> Set a lower follower limit on monsters used: 100 
> Set an upper follower limit that you want to use: 484905517 
> Enter Enemy Lineup(s): quest138-3 
> 
> Calculating with 123 available Monsters and 115 enabled Heroes.
> Starting loop for armies of size 1
> Starting loop for armies of size 2
> Starting loop for armies of size 3+
> 
> Solution for [quest138-3 | Followers: 951,416,500 | a27 a27 w30 f28 w30 a27 <==]:
>   [Followers: 484,622,500 | e30 a28 masterlee:37 e27 <==]
> 
>   49753957 Fights simulated.
>   Total Calculation Time: 32
>   Calc Version: 4.3.2.1c
> 
> Battle Replay (Use on Ingame Tournament Page):
> 432cAAOxtsyUGoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0mk8G88GkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
> 

[Heroes File.txt](https://github.com/Alya-N/C-Hero-Calc/files/3415145/Heroes.File.txt)
[CosmosQuestResults - 145532636.txt](https://github.com/Alya-N/C-Hero-Calc/files/3415146/CosmosQuestResults.-.145532636.txt)
[CosmosQuestResults - 100.txt](https://github.com/Alya-N/C-Hero-Calc/files/3415147/CosmosQuestResults.-.100.txt)

**Comment by Alya-N** [comment]
e27 and a28 cost less than 145532636, so they were not included in the calculations. That's what the lower follower limit does, it excludes monsters that are below that threshold. It's used to exclude monsters that may be too weak and makes the calculation process faster as a result.

**Comment by Vitae666** [comment]
Got it. Wasn't thinking of an individual cost, but an all together cost.
Basically, pulled a me :)

Side question because I'm drawing a blank. 
If I don't want to use Monsters AT ALL, am I correct with my memory being that it's:

Set a lower follower limit on monsters used: -1 
Set an upper follower limit that you want to use: 0 

What I remember is that the lower limit can't be 0 because that is "no limit" tho admittedly I guess it can just be 1 or anything lower than 500,

**Comment by Alya-N** [comment]
Both are 0 in that case. -1 on upper is the "no limit" amount. 0 on lower just includes all monsters and when there's 0 on upper, it won't use any because you wouldn't be able to afford them with 0 followers.

**Comment by Vitae666** [comment]
Thanks :)
