### ISSUE TITLE
Able to set no Monsters for Vboss calc?

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#32]
I know, the easiest way to tell the calc to not use monstes is to set the max followers to 0.
But is the calc able to recognize that it's really a Heroes ONLY boss?
And while at it, know that direct damage Heroes are useless and to use only Heroes that have damage skills? 
Kinda sucks to have the MacroCreator say "Here's your best 20 Heroes!" and all of them are direct damage :)
Tho, something like that would be also MC side somehow.

**Comment by Alya-N** [comment]
Well, direct damage heroes still have some use, mainly tanking for AoE.
And no, calc can't recognize that it's pure HA, sorry.
