### ISSUE TITLE
Help with compiling

### ISSUE THREAD

**Issue by braveslice** [Alya-N/C-Hero-Calc#34]
Hi and thx for great tool. I'm totally new to c++ and while trying to compile current version (4.6.0.1f) I'm getting lots of errors. I tried both make file compiling and command line. The command line compiling worked on my old pc, not sure what has change. Below is link to the compiler message, maybe you find time to see why my compiling fails.

https://www.codepile.net/pile/KARrZRA8

Commands I used: a) mingw32-make and b) g++ -Ofast -std=c++11 -o CosmosQuest main.cpp inputProcessing.cpp cosmosData.cpp battleLogic.cpp base64.cpp -s -static -static-libstdc++ -static-libgcc -pthread

**Comment by Alya-N** [comment]
Well, that's the mingw32-make compile messages, when I use b) the command line option, so providing that could give me more insight into this issue. From what I can see, the error messages are connected to vector handling, which I haven't touched, it's still the same from the Diceycle version as far as I know. 
You are using the 8.2.0 version of MingW32, which, though unlikely, could change some things. The description mentions that the `x86_64-8.1.0-posix-seh-rt_v6-rev0` build is used for compiling, perhaps trying that will work.
I'll still try to see if anything can be done, but I haven't changed the structure of the calc besides adding new heroes, skills and quests.

**Comment by braveslice** [comment]
Yes, `x86_64-8.1.0-posix-seh-rt_v6-rev0` got rid of all errors, left only warnings.

Thx!
