### ISSUE TITLE
Wrong solution to daily 

### ISSUE THREAD

**Issue by braveslice** [Alya-N/C-Hero-Calc#35]
Hey,

This is given as an solution to daily 169: 460fAA1oEXHHLNjmpxzCY5gscAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAimgZLQN5oES0BBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

It leaves James to stand with 15 health, same with ophelia.

E33,auri:1000,scinda:1000,orin:1000,james:1000
ophelia:1 neil:99.4 masterlee:99.4 aneptunius:99.4 raiderrose:99.4 guy:99.4

Thx

**Comment by Alya-N** [comment]
There was a problem with Fairies giving their buff too late after their death.
It should be fixed in the latest version 4.6.0.6g

**Comment by braveslice** [comment]
I appreciate a lot, thank you for your hard work!
