### ISSUE TITLE
DQ solve 169 gives errornous result

### ISSUE THREAD

**Issue by braveslice** [Alya-N/C-Hero-Calc#38]
Happy New Year!
All good things to you for the next 10 years.

Welcome to Diceycle's PvE Instance Solver! v4.6.2.3b
`  Simulating fights by expanding Lineups one by one ...
        [Followers:       0 | minerva:1 masterlee:99.4 neil:99.4 raiderrose:99.4 guy:99.4 aurora:99.4 <==]
Done! (  0 seconds)

Solution for [Followers:       0 | hosokawa:1000 mother:1000 alvitr:1000 athos:1000 sigrun:1000 <==]:
  [Followers:       0 | minerva:1 masterlee:99.4 neil:99.4 raiderrose:99.4 guy:99.4 aurora:99.4 <==]

  112295 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.6.2.3b

Battle Replay (Use on Ingame Tournament Page):
462bAA1oEWbHLjjmExzBY5k8cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArGgajQJ7oEM0Cd6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=`

**************

**EDIT 10 min later or so, removing Neil from the pool returns correct answer:**
 Simulating fights by expanding Lineups one by one ...
        [Followers:       0 | minerva:1 masterlee:99.4 raiderrose:99.4 guy:99.4 anerissa:99.4 aurora:99.4 <==]
Done! (  0 seconds)

Solution for [Followers:       0 | hosokawa:1000 mother:1000 alvitr:1000 athos:1000 sigrun:1000 <==]:
  [Followers:       0 | minerva:1 masterlee:99.4 raiderrose:99.4 guy:99.4 anerissa:99.4 aurora:99.4 <==]

  89089 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.6.2.3b

Battle Replay (Use on Ingame Tournament Page):
462bAA1oEWbHMJjmCxzU45k8cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArGgajQJ7oEM0Cd6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

**Comment by Alya-N** [comment]
From what I see, this bug started occurring after I fixed Aurora and other fairies to buff other units immediately after they die, protecting units behind them from dying to ricochet in certain instances.
However, Neil takes damage from his Dampen ability before the health buff from Aurora is applied, so I'll have to figure out how to fix that as well, since his ability was written before I started updating the calc.

**Comment by Alya-N** [comment]
Happy New Year to you as well! 🎄

**Comment by braveslice** [comment]
Oh you are already working on it. Good luck! And Happy New Year again =)!

**Comment by Alya-N** [comment]
Fixed, now it shows this result with Neil selected:
```
Solution for [Followers:       0 | hosokawa:1000 mother:1000 alvitr:1000 athos:1000 sigrun:1000 <==]:
  [Followers:       0 | minerva:1 masterlee:99.4 raiderrose:99.4 guy:99.4 neil:99.4 aurora:99.4 <==]

  813 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.6.2.3c

Battle Replay (Use on Ingame Tournament Page):
462cAA1oEWbHMJjmCxy445k8cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArGgajQJ7oEM0Cd6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
```

**Comment by braveslice** [comment]
Good way to start the new year! Cheers!
