### ISSUE TITLE
Incorrect solution

### ISSUE THREAD

**Issue by obscurans** [Alya-N/C-Hero-Calc#40]
Solution for [Followers:       0 | ophelia:1000 hattori:1000 brynhildr:1000 maraudermagnus:1000 aural:1000 <==]:
  [Followers:       0 | neil:99.4 kedari:12 minerva:99.5 raiderrose:99.4 aurora:99.4 guy:99.3 <==]

  5255821 Fights simulated.
  Total Calculation Time: 2
  Calc Version: 4.6.2.3b

Battle Replay (Use on Ingame Tournament Page):
462bAAuOOYsYNbjuExzJ45gsbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1egVvQJFoGH0CP6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

**Comment by Alya-N** [comment]
Pretty sure I've fixed it in version c, but I'll check again

**Comment by Alya-N** [comment]
Yeah, 4.6.2.3c doesn't give a solution for those 6 heroes.

**Comment by obscurans** [comment]
Ack, sorry for noise - my dev branch needs a pull
