### ISSUE TITLE
Incorrect result

### ISSUE THREAD

**Issue by obscurans** [Alya-N/C-Hero-Calc#41]
Solution for [Followers:       0 | dagda:1000 pontus:1000 cliodhna:1000 hidoka:1000 kedari:1000 <==]:
  [Followers:       0 | kedari:12 masterlee:99.4 raiderrose:99.4 guy:99.3 minerva:99.5 aurora:99.4 <==]

  2835905 Fights simulated.
  Total Calculation Time: 1
  Calc Version: 4.6.2.3c

Battle Replay (Use on Ingame Tournament Page):
462cAAxYwWbHMJjmCxvW47k8cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp+gSbQMDoFp0DF6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

**Comment by Alya-N** [comment]
Thank you. Clio hasn't been taking Aurora's buff into account.
Should be fixed in version 4.6.2.3d
```
Solution for [Followers:       0 | dagda:1000 pontus:1000 cliodhna:1000 hidoka:1000 kedari:1000 <==]:
  [Followers:       0 | kedari:12 guy:99.3 minerva:99.5 raiderrose:99.4 masterlee:99.4 aurora:99.4 <==]

  817 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.6.2.3d

Battle Replay (Use on Ingame Tournament Page):
462dAAxYwYLG9bjuExyzY5k8cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp+gSbQMDoFp0DF6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
```
