### ISSUE TITLE
Wrong results - Daily 22FEB 185

### ISSUE THREAD

**Issue by braveslice** [Alya-N/C-Hero-Calc#42]
Wrong result. This lineup seems quite hard to compute :o 

Line is correct if we add Neil.4 to end.

` Simulating fights by expanding Lineups one by one ...
        [Followers:       0 | masterlee:99.6 pokerface:99.4 raiderrose:99.4 minerva:25 aurora:99.6 <==]
Done! (  0 seconds)

Solution for [Followers:       0 | crei:1000 bavah:1000 hosokawa:1000 cliodhna:1000 tr0n1x:1000 <==]:
  [Followers:       0 | masterlee:99.6 pokerface:99.4 raiderrose:99.4 minerva:25 aurora:99.6 <==]

  79299 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.7.0.2test_broken_res_3

Battle Replay (Use on Ingame Tournament Page):
470tAAs2PW3HMJjmtMjJ48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANloFf0CsaBgdAi+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==`

**Comment by Alya-N** [comment]
Weirdly enough, I can't replicate it, despite the version numbers being the same. and I don't think it's a problem with cqdata.txt either. I'll try to figure out how to replicate it, but the calc currently gives me this: 
```
Solution for [Followers:       0 | crei:1000 bavah:1000 hosokawa:1000 cliodhna:1000 tr0n1x:1000 <==]:
  [Followers:       0 | masterlee:99.6 pokerface:99.4 minerva:25 raiderrose:99.4 aurora:99.6 <==]

  309 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.7.0.2test_broken_res_3

Battle Replay (Use on Ingame Tournament Page):
470tAAs2PW3HNaZGExzJ48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANloFf0CsaBgdAi+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
```
EDIT: managed to replicate it and now I have questions as to how Clio got such a huge buff in-game. Will investigate.

**Comment by Alya-N** [comment]
I've changed how Clio works, since she didn't take into account some of the enemy buffs, and now there shouldn't be issues with her in version **4.7.0.2test_broken_res_4**
