### ISSUE TITLE
Unsuccessful Success v4.7.1.1e

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#44]
Successfully got enemy lineup for DQ154 - E33,W33,acrei:79,alvitr:1000,agatha:1000
DQ solution accepted by server
Successfully got enemy lineup for DQ154 - E33,W33,acrei:79,alvitr:1000,agatha:1000

Welcome to Diceycle's PvE Instance Solver! v4.7.1.1e
If you are new to using this Calculator I recommend reading the Github README.

Using specified File...

Enter your Heroes with levels. Press enter after every Hero.
Press enter twice or type done to proceed without inputting additional Heroes.
Enter Hero 1: alpha:99.2
Enter Hero 2: athos:99.2
Enter Hero 3: rei:99.2
Enter Hero 4: atzar:66.0
Enter Hero 5: tiny:99.2
Enter Hero 6: nebra:99.2
Enter Hero 7: shygu:99.2
Enter Hero 8: thert:99.2
Enter Hero 9: lordkirk:99.2
Enter Hero 10: neptunius:99.2
Enter Hero 11: rigr:61.0
Enter Hero 12: ageum:99.2
Enter Hero 13: hosokawa:99.2
Enter Hero 14: takeda:99.2
Enter Hero 15: hirate:99.2
Enter Hero 16: hattori:99.2
Enter Hero 17: sparks:99.4
Enter Hero 18: leaf:99.2
Enter Hero 19: masterlee:99.2
Enter Hero 20: kumusan:52.0
Enter Hero 21: mahatma:99.2
Enter Hero 22: jade:99.2
Enter Hero 23: edana:99.2
Enter Hero 24: dybbuk:99.2
Enter Hero 25: athert:99.2
Enter Hero 26: alordkirk:99.2
Enter Hero 27: aneptunius:99.2
Enter Hero 28: ahosokawa:99.2
Enter Hero 29: atakeda:91.0
Enter Hero 30: ahattori:13.0
Enter Hero 31: raiderrose:99.6
Enter Hero 32: buccaneerbeatrice:99.2
Enter Hero 33: ruin:99.2
Enter Hero 34: blossom:64.0
Enter Hero 35: aurora:99.6
Enter Hero 36: b-day:99.2
Enter Hero 37: cloud:99.6
Enter Hero 38: gizmo:99.2
Enter Hero 39: lili:99.2
Enter Hero 40: adam:39.0
Enter Hero 41: done
Set a lower follower limit on monsters used: 910000000
Set an upper follower limit that you want to use: 4224499855
Enter Enemy Lineup(s): e33,w33,acrei:79,alvitr:1000,agatha:1000

Calculating with 12 available Monsters and 40 enabled Heroes.
Starting loop for armies of size 1
Starting loop for armies of size 2
Starting loop for armies of size 3
Starting loop for armies of size 4

Solution for [Followers: 1,940,354,500 | agatha:1000 alvitr:1000 acrei:79 w33 e33 <==]:
  [Followers:       0 | ageum:99.2 raiderrose:99.6 aurora:99.6 masterlee:99.2 <==]

  1285233 Fights simulated.
  Total Calculation Time: 3
  Calc Version: 4.7.1.1e

Battle Replay (Use on Ingame Tournament Page):
471eAAo2NYTHsnj1mxoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADVaBPdA2c8IRBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Do you want to calculate more lineups? (y/n): y
Enter Enemy Lineup(s):

**Comment by Vitae666** [comment]
I let the game do the solving so I could move on, but 155 had the same issue

Successfully got enemy lineup for DQ155 - W33,E33,W33,dybbuk:1000,orin:1000
DQ solution accepted by server
Successfully got enemy lineup for DQ155 - W33,E33,W33,dybbuk:1000,orin:1000

Welcome to Diceycle's PvE Instance Solver! v4.7.1.1e
If you are new to using this Calculator I recommend reading the Github README.

Using specified File...


Enter your Heroes with levels. Press enter after every Hero.
Press enter twice or type done to proceed without inputting additional Heroes.
Enter Hero 1: alpha:99.2
Enter Hero 2: athos:99.2
Enter Hero 3: rei:99.2
Enter Hero 4: atzar:67.0
Enter Hero 5: tiny:99.2
Enter Hero 6: nebra:99.2
Enter Hero 7: shygu:99.2
Enter Hero 8: thert:99.2
Enter Hero 9: lordkirk:99.2
Enter Hero 10: neptunius:99.2
Enter Hero 11: rigr:63.0
Enter Hero 12: ageum:99.2
Enter Hero 13: hosokawa:99.2
Enter Hero 14: takeda:99.2
Enter Hero 15: hirate:99.2
Enter Hero 16: hattori:99.2
Enter Hero 17: sparks:99.4
Enter Hero 18: leaf:99.2
Enter Hero 19: masterlee:99.2
Enter Hero 20: kumusan:52.0
Enter Hero 21: mahatma:99.2
Enter Hero 22: jade:99.2
Enter Hero 23: edana:99.2
Enter Hero 24: dybbuk:99.2
Enter Hero 25: athert:99.2
Enter Hero 26: alordkirk:99.2
Enter Hero 27: aneptunius:99.2
Enter Hero 28: ahosokawa:99.2
Enter Hero 29: atakeda:91.0
Enter Hero 30: ahattori:13.0
Enter Hero 31: raiderrose:99.6
Enter Hero 32: buccaneerbeatrice:99.2
Enter Hero 33: ruin:99.2
Enter Hero 34: blossom:64.0
Enter Hero 35: aurora:99.6
Enter Hero 36: b-day:99.2
Enter Hero 37: cloud:99.6
Enter Hero 38: gizmo:99.2
Enter Hero 39: lili:99.2
Enter Hero 40: adam:39.0
Enter Hero 41: done
Set a lower follower limit on monsters used: 910000000
Set an upper follower limit that you want to use: 4226299855
Enter Enemy Lineup(s): w33,e33,w33,dybbuk:1000,orin:1000

Calculating with 12 available Monsters and 40 enabled Heroes.
Starting loop for armies of size 1
Starting loop for armies of size 2
Starting loop for armies of size 3
Starting loop for armies of size 4

Solution for [Followers: 2,878,436,500 | orin:1000 dybbuk:1000 w33 e33 w33 <==]:
  [Followers:       0 | alpha:99.2 raiderrose:99.6 aurora:99.6 masterlee:99.2 <==]

  2332681 Fights simulated.
  Total Calculation Time: 6
  Calc Version: 4.7.1.1e

Battle Replay (Use on Ingame Tournament Page):
471eAAhONYTHsnj1mxoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADJaBddAQiCQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=


Do you want to calculate more lineups? (y/n): y
Enter Enemy Lineup(s):

**Comment by Vitae666** [comment]
AND 156.....

Successfully got enemy lineup for DQ156 - A33,F33,boson:1000,pontus:1000,hans:1000
DQ solution accepted by server
Successfully got enemy lineup for DQ156 - A33,F33,boson:1000,pontus:1000,hans:1000

Welcome to Diceycle's PvE Instance Solver! v4.7.1.1e
If you are new to using this Calculator I recommend reading the Github README.

Using specified File...


Enter your Heroes with levels. Press enter after every Hero.
Press enter twice or type done to proceed without inputting additional Heroes.
Enter Hero 1: alpha:99.2
Enter Hero 2: athos:99.2
Enter Hero 3: rei:99.2
Enter Hero 4: atzar:67.0
Enter Hero 5: tiny:99.2
Enter Hero 6: nebra:99.2
Enter Hero 7: shygu:99.2
Enter Hero 8: thert:99.2
Enter Hero 9: lordkirk:99.2
Enter Hero 10: neptunius:99.2
Enter Hero 11: rigr:63.0
Enter Hero 12: ageum:99.2
Enter Hero 13: hosokawa:99.2
Enter Hero 14: takeda:99.2
Enter Hero 15: hirate:99.2
Enter Hero 16: hattori:99.2
Enter Hero 17: sparks:99.4
Enter Hero 18: leaf:99.2
Enter Hero 19: masterlee:99.2
Enter Hero 20: kumusan:52.0
Enter Hero 21: mahatma:99.2
Enter Hero 22: jade:99.2
Enter Hero 23: edana:99.2
Enter Hero 24: dybbuk:99.2
Enter Hero 25: athert:99.2
Enter Hero 26: alordkirk:99.2
Enter Hero 27: aneptunius:99.2
Enter Hero 28: ahosokawa:99.2
Enter Hero 29: atakeda:91.0
Enter Hero 30: ahattori:13.0
Enter Hero 31: raiderrose:99.6
Enter Hero 32: buccaneerbeatrice:99.2
Enter Hero 33: ruin:99.2
Enter Hero 34: blossom:64.0
Enter Hero 35: aurora:99.6
Enter Hero 36: b-day:99.2
Enter Hero 37: cloud:99.6
Enter Hero 38: gizmo:99.2
Enter Hero 39: lili:99.2
Enter Hero 40: adam:39.0
Enter Hero 41: done
Set a lower follower limit on monsters used: 910000000
Set an upper follower limit that you want to use: 4226299855
Enter Enemy Lineup(s): a33,f33,boson:1000,pontus:1000,hans:1000

Calculating with 12 available Monsters and 40 enabled Heroes.
Starting loop for armies of size 1
Starting loop for armies of size 2
Starting loop for armies of size 3
Starting loop for armies of size 4
Starting loop for armies of size 5+

Solution for [Followers: 2,014,477,000 | hans:1000 pontus:1000 boson:1000 f33 a33 <==]:
  [Followers:       0 | alpha:99.2 masterlee:99.2 raiderrose:99.6 cloud:99.6 aurora:99.6 <==]

  4989352 Fights simulated.
  Total Calculation Time: 21
  Calc Version: 4.7.1.1e

Battle Replay (Use on Ingame Tournament Page):
471eAAhONWbGsJj2Zx7J48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOVoEm0Dg6Ag0CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==


Do you want to calculate more lineups? (y/n): y
Enter Enemy Lineup(s):

**Comment by Vitae666** [comment]
Of those 3, there were 3 common heroes: raiderrose:99.6 aurora:99.6 masterlee:99.2
I took Aurora out of the calc, as a curiosity and it worked. I mived on.
Not saying Aurora is the problem, but at least 1 of those 3 might need a looking at. Likely a P6 thing?

**Comment by Alya-N** [comment]
Ummm.... That's not even the main branch calc, that's the calc that's going to be released if promo 6 is fixed by devs in the game o.O
Main branch is version v4.7.1.1j_broken_res right now.

**Comment by Vitae666** [comment]
Oh. Ok. Sorry. I went for the one that was newest.
I really don't know to much about how things are done on github. What's the reasoning for publishing a commit that isn't meant to be used? Incase your version on your computer gets deleted?

**Comment by Alya-N** [comment]
I'm not entirely sure how you even got that version, it's stored on a different branch. Through Network tab?
And I do have my reasons for it to be there, one of which is making sure that I didn't miss something when updating the fixed res version of the calc.

**Comment by Vitae666** [comment]
Yeap. Thru network. That's where I go to see if you or Matt have updates.
All good tho. I'll keep in kind that the upper line is the proper commits.

**Comment by Alya-N** [comment]
Well, now that revive's fixed, all those solutions work, so I can close this thread now :D
