### ISSUE TITLE
False positive ("FATAL ERROR")

### ISSUE THREAD

**Issue by Simoris** [Alya-N/C-Hero-Calc#45]
`Solution for [Followers: 220,678,435,000 | e40 w40 a40 f41 a41 <==]:
  [Followers:       0 | masterlee:99.6 apontus:99.5 raiderrose:99.5 awanderer:99.6 adagda:99.6 <==]

  51452 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.7.1.1j_broken_res

Battle Replay (Use on Ingame Tournament Page):
470jAAs2PVHHcJjuux6uY8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE8oE6o1CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

This does not beat the lineup!!!
FATAL ERROR!!! Please comment this output in the Forums!`

**Comment by Alya-N** [comment]
It appears I didn't fully finish coding the optimization process to consider revive units, and since aWanderer doesn't have any special skills on top of him, the process thought he should revive anywhere. I've fixed it in the new version.
