### ISSUE TITLE
wrong result 4.7.2.0a

### ISSUE THREAD

**Issue by DevilPF** [Alya-N/C-Hero-Calc#46]
Hi, one false-positive result (it's defeat in game):

Solution for [Followers:       0 | gurth:1000 dullahan:1000 cliodhna:1000 nebra:1000 neil:1000 <==]:
  [Followers:       0 | leprechaun:99.6 guy:99.4 masterlee:99.6 <==]
  Calc Version: 4.7.2.0a

Battle Replay (Use on Ingame Tournament Page):
472aAAsGPYLHLNjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmWgTXQMDoEC0C46AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

**Comment by DevilPF** [comment]
btw is there way to skip first solution and continue to search more? Or to write out all found solutions or something similar?

**Comment by Vitae666** [comment]
> btw is there way to skip first solution and continue to search more? Or to write out all found solutions or something similar?

default.cqconfig
STOP_FIRST_SOLUTION FALSE

**Comment by DevilPF** [comment]
If I'm reading the code right, that would only work if the solution have used followers and not for any pure heroes solutions as is this.

**Comment by Alya-N** [comment]
Sorry, accidentally disabled Clio's skill while doing some code changes, my bad. Fixed in 4.7.2.0b

**Comment by DevilPF** [comment]
No problem, thank you for the quick fix :)
