### ISSUE TITLE
Wrong solution involving silex

### ISSUE THREAD

**Issue by braveslice** [Alya-N/C-Hero-Calc#47]
`Solution for [Followers: 1,940,354,500 | geror:3000 silex:7000 carl:3000 e33 w33 <==]:
  [Followers:       0 | youngpyros:7 masterlee:99.6 aneptunius:99.4 <==]

  10673 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.7.3.0e

Battle Replay (Use on Ingame Tournament Page):
eyJzZXR1cCI6Wy0yMTAsLTEwNCwtMTIzLC0xLC0xLC0xXSwic2hlcm8iOnsiMTIxIjo5OSwiMTAyIjo5OSwiMjA4Ijo3fSwic3Byb21vIjp7IjEyMSI6NCwiMTAyIjo2fSwicGxheWVyIjpbLTM0LC0yMTcsLTEyLDEyOSwxMzEsLTFdLCJwaGVybyI6eyIxMCI6MzAwMCwiMjE1Ijo3MDAwLCIzMiI6MzAwMH0sInBwcm9tbyI6e319`

Disabling egg line does not make solution right.

**Comment by Alya-N** [comment]
Pretty sure this bug was fixed in version `4.7.3.0f - Fixed S5 Reflect to be synced with Easter Pyros Reflect`.
Version 4.7.3.0g does not show it as a solution.

**Comment by braveslice** [comment]
My bad. I extracted the new version to wrong folder. Keep up the good work, thx!
