### ISSUE TITLE
incorrect solve by calculator

### ISSUE THREAD

**Issue by burgy001** [Alya-N/C-Hero-Calc#48]
CQ Calc spat out an incorrect solve, it said that A27,F26,W26,W26,abavah:76 was solveable with dullahan:99.2 sexysanta:99.6 retia:27 egg:99.6 <== which it really isn't a solution that works as retia 27 leaves A27 at 4 hp, even with retia:28 which does get a kill on A27 and then buffs santa it still fails as buffed santa dies in one hit to F26.

**Comment by Alya-N** [comment]
It's fixed in v4.7.3.0h, Retia wasn't considering armor in her skill check.
