### ISSUE TITLE
Solution Failing on v4.7.4.1a

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#49]
Successfully got enemy lineup for DQ172 - A33,E33,A33,egg:3000,zaytus:6000
Successfully got quests from server
DQ solution accepted by server
Successfully got enemy lineup for DQ172 - A33,E33,A33,egg:3000,zaytus:6000

Solution for [Followers: 3,045,104,500 | zaytus:6000 egg:3000 a33 e33 a33 <==]:
  [Followers:       0 | minerva:99.2 raiderrose:99.6 arei:99.2 retia:72 ageum:99.2 aurora:99.6 <==]

Battle Replay (Use on Ingame Tournament Page):
eyJzZXR1cCI6Wy0xNzUsLTEzNCwtNjksLTE5MiwtNzIsLTE0OV0sInNoZXJvIjp7IjE0NyI6OTksIjcwIjo5OSwiMTkwIjo3MiwiNjciOjk5LCIxMzIiOjk5LCIxNzMiOjk5fSwic3Byb21vIjp7IjE0NyI6NiwiNzAiOjIsIjY3IjoyLCIxMzIiOjYsIjE3MyI6Mn0sInBsYXllciI6Wy00MywtMjA4LDEyOCwxMjksMTI4LC0xXSwicGhlcm8iOnsiMjA2IjozMDAwLCI0MSI6NjAwMH0sInBwcm9tbyI6e319

![image](https://user-images.githubusercontent.com/9310914/82868836-4f249980-9efb-11ea-9acc-e1e9131aeb49.png)

**Comment by Alya-N** [comment]
This bug I believe was actually quite a complicated one, which is why it wasn't fixed for a while. 
New calc doesn't show a solution with these heroes, but Retia himself has been changed so he no longer gives the buff to the unit behind him.
