### ISSUE TITLE
Solution Failing on v4.7.5.1b

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#52]
Enter Enemy Lineup(s): w33,a33,jalrok:4000,aquortis:7000,frosty:5000
Solution for [Followers: 1,959,498,000 | frosty:5000 aquortis:7000 jalrok:4000 a33 w33 <==]:
  [Followers:       0 | adam:39 masterlee:99.2 raiderrose:99.6 buccaneerbeatrice:99.2 lili:99.2 aurora:99.6 <==]

Battle Replay (Use on Ingame Tournament Page):
eyJzZXR1cCI6Wy0yMDAsLTEwNCwtMTM0LC0xMzUsLTE4NywtMTQ5XSwic2hlcm8iOnsiMTQ3Ijo5OSwiMTg1Ijo5OSwiMTMzIjo5OSwiMTMyIjo5OSwiMTAy
Ijo5OSwiMTk4IjozOX0sInNwcm9tbyI6eyIxNDciOjYsIjE4NSI6MiwiMTMzIjoyLCIxMzIiOjYsIjEwMiI6Mn0sInBsYXllciI6Wy0xMzgsLTI2LC0yMjgs
MTI4LDEzMSwtMV0sInBoZXJvIjp7IjIyNiI6NDAwMCwiMjQiOjcwMDAsIjEzNiI6NTAwMH0sInBwcm9tbyI6e319

![image](https://user-images.githubusercontent.com/9310914/84953497-a284a480-b0c1-11ea-970e-b5ba232e6821.png)

Per CQMC
Successfully got enemy lineup for DQ170 - W33,A33,jalrok:4000,aquortis:7000,frosty:5000
Successfully got quests from server
DQ solution accepted by server
Successfully got enemy lineup for DQ170 - W33,A33,jalrok:4000,aquortis:7000,frosty:5000

**Comment by Alya-N** [comment]
Well, the solution works now, and the new version I just updated shows an equally valid solution.
