### ISSUE TITLE
Likely dumb question regarding calculation speed

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#53]
Ok, so, there's 3 ways that the calc can be used. 
Using WB's as a simple example:
1. loc:1, moak:1 (now that I know this one)
2. loc:1 > Yes new lineup > moak:1
3. loc:1 > close calc > moak:1
^^ Hope those made sense

Do any of those perform better?
Obviously, 3rd starts fresh. But is anything retained in any way for 1st and 2nd that not as many calcs are done or are done quicker?
Or would the calc take the exact same amount of time for each one regardless?
I'm always running something or other on this 10+yr old laptop with just 4GB RAM. And even when I'm not, I can run the same calc 5 times and get 5 different lengths of time. So I really have no way of knowing. 
Was just a curiosity of mine. Something to, potentially, shave some time off the calcs.

EDIT:
Also asking because at least with DQ's the 2nd and 3rd you also might get that "do you wish to continue" bit, where as it isn't present in the 1st since that's, I guess, more for WB's? As it is, I don't always get the "wish to continue" in the 2nd and 3rd DQ's at times. So, there's something extra going on that I just don't get :)

**Comment by Alya-N** [comment]
Pretty sure those are the exact same, 1 & 2 just don't require you to input your heroes again.
As for varying speed, I think that just depends on how fast the PC wants to run calc at the time.
