### ISSUE TITLE
Stopping at 1 Hero solution that is also a draw.

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#54]
```
Successfully got enemy lineup for DQ82 - F22,A22,A22,E22,john:47
Successfully got quests from server
DQ solution accepted by server
Successfully got enemy lineup for DQ82 - F22,A22,A22,E22,john:47

Enter Enemy Lineup(s): f22,a22,a22,e22,john:47

Calculating with 8 available Monsters and 40 enabled Heroes.
Starting loop for armies of size 1

Solution for [Followers: 110,999,500 | john:47 e22 a22 a22 f22 <==]:
  [Followers:       0 | retia:99 <==]

  47 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.8.0.2a

Battle Replay (Use on Ingame Tournament Page):
eyJzZXR1cCI6Wy0xOTIsLTEsLTEsLTEsLTEsLTFdLCJzaGVybyI6eyIxOTAiOjk5fSwic3Byb21vIjp7fSwicGxheWVyIjpbLTIyMyw4NSw4NCw4NCw4Niwt
MV0sInBoZXJvIjp7IjIyMSI6NDd9LCJwcHJvbW8iOnt9fQ==
```

My cqconfig usually has
STOP_FIRST_SOLUTION TRUE
So, as a curiosity, I changed it to
STOP_FIRST_SOLUTION FALSE
And that didn't do anything. Still stopped at Retia being the solution. But didn't expect it to really. Was just the QA in me :)
Either way, Draw solution on what should be a win.

**Comment by Alya-N** [comment]
Well, the purpose of `STOP_FIRST_SOLUTION FALSE` is to find the cheapest solution in terms of followers, so it's still going to stop on the same solution if it doesn't use any followers. Mostly an artifact from the times when heroes were far less common and followers were the main way of clearing quests.
As for the bug itself, I see that Retia's health buff is triggered after John's AoE, which I'll try to figure out how to fix, so thank you for the bug report.
